pharo-spec/ScriptableDebugger

- Sindarin-Tests/SindarinBytecodeToASTCacheTest.class.st
- Sindarin-Tests/SindarinBytecodeToASTCacheTestd.class.st
- Sindarin/SindarinBytecodeToASTCache.class.st
- Sindarin/SindarinDebugger.class.st
Experiments of node access while stepping in Sindarin.
Now it lazily builds a cache of all possible bytecode offsets to their associated AST nodes and accesses this cache instead of searching nodes in the IR each time.
> Node access optimization

- Sindarin-Tests/SindarinBytecodeToASTCacheTest.class.st
- Sindarin-Tests/SindarinDebugSessionTest.class.st
- Sindarin-Tests/SindarinDebuggerTests.class.st
- Sindarin/DebugSession.extension.st
- Sindarin/SindarinDebugSession.class.st
- Sindarin/SindarinDebugger.class.st
Now `SindarinDebugSession` is not a subclass of `DebugSession` anymore, but delegates to an instance of `DebugSession`  instead.
Also did a pass over tests.
> Breaking sin debug session inheritance refactoring

- SindarinInterpreterAPI.md
SindarinAdapter>>#debug: is actually on the class side
> Fix typo in documentation

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/Context.extension.st
- Sindarin/SindarinDebugger.class.st
- remove Context>>#temporaries
- remove SindarinDebugger>>#temporaries
- remove test
there are no senders of #temporaries from the package. Fixes #8
> - remove Context>>#temporaries

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
The test #testIsExecutionFinished is cleaned to not depend on the particular implementation of Process>>#terminate method. And this clean version actually shows that the  debugger does not work correctly. Therefore the test is disabled on CI for now.
This change is required to properly integrate #realActiveProcess PR (https://github.com/pharo-project/pharo/pull/8567) into Pharo without breaking the existing tests of Sindarin project.
Once Pharo PR  will be integrated the fix for Sindarin test will be pushed. The SindarinDebugger methods are required for the this fix but they do not break other parts in current image and therefore they are included here.
**IMPORTANT**: integrate it into Pharo10 branch or do a proper release version. It seems we lost the static versions with this project. …
> Prepare for #realActiveProcess integration in Pharo

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #19
In `SindarinDebugger`, when you wanted to skip an assignment with the `skip` method; it was assigning `nil` to the variable that was supposed to be assigned, while you'd expect it to completely skip the assignment so that the assigned variable keep the same value as before the assignment.
Furthermore, to go over the assignment, the `skipAssignmentNodeWith:` was skipping an arbitrary number of bytes. As a result, sometimes, too many pc were skipped and some arguments were missing on the stack. In other cases, the replacement value that should have been assigned to the variable wasn't actually assigned.
To fix this, now, I've made a version `skipAssignmentNodeCompletely` that completely goes over the assignment by skipping the exact number of bytes there are in the bytecode that …
> Correction of skipAssignment command that had wrong behaviour

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/RBBlockDefinitionSearchingVisitor.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #21 
In `SindarinDebugger`, the `stepToReturn` command didn't step to returns in blocks, as its implementation was using `stepOver`.
I've tried an implementation that uses `stepThrough`, which indeed fixed the problem, but that is problematic as `stepThrough` actually steps beyond exception signals if these exceptions are resumable.
I've also tried an implementation that uses `stepInto`, which also fixed the problem, but that is problematic as `stepInto` stops on halts, which is not the expected behaviour.
Now, the implementation I've done matches all 3 goals:
While a return hasn't been reached in the lexical context or an exception hasn't been signaled, we `stepOver` (to step on exceptions but not halts) except if we are on a message node that has, as a receiver or as an argument, …
> Correction of stepToReturn command to be able to step to non-local returns.

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #25.
Some changes were made in the Pharo repo to use the correct API of the class `Process`: https://github.com/pharo-project/pharo/pull/8567/files#diff-ba7fcd4a659f90f879b1491dc051a7f1566317e9eecde109cdb67e56618177db
These changes have been integrated into this repo by #43 but some changes in the method have been forgotten:
```Smalltalk
SindarinDebugger>>#isExecutionFinished
^ process isTerminating
```
should actually be 
```Smalltalk
SindarinDebugger>>#isExecutionFinished
^ process isTerminated
```
so that `testIsExecutionFinished` becomes green
> Synchronising with changes made in Pharo repo a year and a half ago

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #31 
When you were skipping a message, the result of the message send was nil.
So, if you skipped the message `+` in ```3 + 2```, the result was nil. However, you'd expect that the message `+` is not sent to 3 and that the result of skipping the message would therefore be the receiver of the message itself: 3.
I fixed the skip command so that the result of skipping a message send is the receiver of the message itself.
Done with @DanielCamSan
> Fixing skip command so that it leaves the receiver on the stack instead of putting nil on the stack

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/RBBlockDefinitionSearchingVisitor.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #34.
When a message send was skipped, it used increment the pc of one byte.
However, some message send bytecodes are made up of 2 bytes, so skipping 1 byte is arbitrar.
So, I fixed it so that it skips the exact number of bytes contained in the bytecode.
#33 needs to be merged first.
> Fixing skip so that it skips the right number of bytes to skip message send bytecodes

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #39 
When the sindarin debugger is stopped on a method node, the skip command doesn't do anything (it doesn't skip it nor it steps it), which causes the skipUpTo command to enter an infinite loop.
I fixed it so that the skip command steps when the current node is a method node, because the bytecodes on which we are stopped are bytecodes that are invisible to users and thus, that they don't want to skip
> 39 skip doesnt skip method nodes

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/SindarinDebugger.class.st
Fixes #38 
When `skip` met a block node for a block creation, it didn't do anything and caused skipUpTo to enter an infinite loop and freeze the image.
I fixed it by skipping the block creation byte code and pushing nil on the stack instead of the block.
> Fixing skip so that it skips block creations

- Sindarin/SindarinDebugger.class.st
Fixes #52 
This allows to push the required arguments on the stack for the next instruction to be executed. If these arguments are not stepped, then `skipUpTo:` would do nothing and enter an infinite loop.
> skipBlockNode now stepsToFirstInterestingBytecode after skipping the block creation

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/Context.extension.st
- Sindarin/DebugSession.extension.st
- Sindarin/InstructionStream.extension.st
- Sindarin/Process.extension.st
- Sindarin/RBAssignmentNode.extension.st
- Sindarin/RBBlockNode.extension.st
- Sindarin/RBMessageNode.extension.st
- Sindarin/RBProgramNode.extension.st
- Sindarin/RBReturnNode.extension.st
- Sindarin/SindarinDebugger.class.st
Fixes #51.
skip used to step over jump bytecodes. Notably, if a comparison before a `ifTrue:ifFalse:`message was skipped, it used to skip the comparison and then step the jumpIfFalse bytecode. As this bytecode expected a boolean on the stack (the result of the comparison that has been skipped) and as the result on the stack is (probably) not a boolean, an exception `MustBeBoolean` was raised and  was not handled. As a result, `skipUpTo` entered an infinite loop because we would never reach the aimed node.
Now, skips stops on jump bytecodes (notably on `ifTrue:ifFalse` messages) and manages these bytecodes separately: it pops the argument if it has one (this is the case for jumpTrue: and jumpFalse: bytecodes) and it simply does not execute the jump bytecode. Then, it steps to the first …
> skip  now ignores jumps

- Sindarin-Tests/SindarinDebuggerTest.class.st
- Sindarin/DebugSession.extension.st
- Sindarin/NodeNotInASTError.class.st
- Sindarin/NotValidPcError.class.st
- Sindarin/OCBytecodeToASTCache.extension.st
- Sindarin/RBBlockNode.extension.st
- Sindarin/RBMethodNode.extension.st
- Sindarin/RBProgramNode.extension.st
- Sindarin/SindarinDebugger.class.st
Fixes #30.
Needs #53  and  #54  to be merged first.
This PR introduces a new JumpToCaret command that allows to move the program execution to the first PC associated to the specific AST node associated to where the caret has been placed.
The command itself can be accessed via the advanced steps menu in the debugger toolbar:
You should put your caret somewhere in the code before using this command, otherwise it will go back to the beginning of the method (even before the creation of temporaries).
Tutorial: What you can do with JumpToCaret
- Everything that you can do with SkipUpTo:
* Jump to caret forward to skip instructions to caret:
In the screnshot below, `a`  is equal to 1 and we jump to caret that is on the `a * 42` message node:
After jumping to caret, the next instruction that will …
> [New Feature] Adding a JumpToCaret command to move the caret back and forth in the debugger suspended context without executing anything in between

- src/Sindarin/InstructionStream.extension.st
#willJumpIfFalse is already a method present un Debbuging-Core in Pharo.
This method creates a clash with the one already in Pharo and need to be removed.
> Remove #willJumpIfFalse

- src/Sindarin-Tests/SindarinDebuggerTest.class.st
See discussion there: https://github.com/pharo-spec/ScriptableDebugger/pull/76
Remove unimplemented method calls to use the right methods
> Remove unimplemented calls

- src/Sindarin-Tests/SindarinDebuggerTest.class.st
This PR propses to fix a failing test in Pharo 12, thanks to @StevenCostiou.
This started to fail since the logic of the simulation changed somewhere (meaning less or more bytecodes executed, or less or more contexts on the stack).
> Fix failing test in Pharo 12

- Sindarin-Tests/SindarinDebuggerTest.class.st
> [P11] fixing removed selectors whose senders have not been updated

- src/Sindarin-Tests/SindarinDebugSessionMock.class.st
- src/Sindarin-Tests/SindarinDebugSessionTest.class.st
- src/Sindarin-Tests/SindarinDebuggerTest.class.st
- src/Sindarin-Tests/package.st
Reverts pharo-spec/ScriptableDebugger#90
The PR chnaged the master branch, it should have been against Pharo12
> Revert "Fix #87. Update a test to use the new name of a method"

- src/Sindarin-Tests/SindarinDebugSessionMock.class.st
- src/Sindarin-Tests/SindarinDebugSessionTest.class.st
- src/Sindarin-Tests/SindarinDebuggerTest.class.st
- src/Sindarin-Tests/package.st
> Fix testIsAboutToInstantiateClass

- src/Sindarin/ASTAssignmentNode.extension.st
- src/Sindarin/ASTBlockNode.extension.st
- src/Sindarin/ASTMessageNode.extension.st
- src/Sindarin/ASTMethodNode.extension.st
- src/Sindarin/ASTProgramNode.extension.st
- src/Sindarin/ASTReturnNode.extension.st
- src/Sindarin/RBAssignmentNode.extension.st
- src/Sindarin/RBBlockDefinitionSearchingVisitor.class.st
- src/Sindarin/RBMessageNode.extension.st
- src/Sindarin/RBReturnNode.extension.st
> Update classes of extensions
